[tool.black]
line-length = 120
target-version = ['py311']

[tool.docformatter]
blank = true
recursive = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = "3.11"
strict = true
